/**
 * Apr 13, 2018 1:38:25 PM
 */
package com.gnv.vnm.selfcare.fcmclient.enums;

/**
 * @author nandipinto
 *
 */
public enum LmsConfigNames {
	
	CORE_BALANCE_MIN_AMOUNT,
	POPUP_NOTIF_MAX_SHOW_COUNT,
	
	POPUP_NOTIF_HUNGRY_TITLE_EN,
	POPUP_NOTIF_HUNGRY_TITLE_VI,
	POPUP_NOTIF_HUNGRY_TEXT_EN,
	POPUP_NOTIF_HUNGRY_TEXT_VI,
	
	POPUP_NOTIF_FULL_TITLE_EN,
	POPUP_NOTIF_FULL_TITLE_VI,
	POPUP_NOTIF_FULL_TEXT_EN,
	POPUP_NOTIF_FULL_TEXT_VI,
	
	POPUP_NOTIF_IMAGE_HUNGRY,
	POPUP_NOTIF_IMAGE_FULL,
	POPUP_NOTIF_DAYS,
	POPUP_NOTIF_HOURS,
	
	RECHARGE_REMINDER_TITLE_EN,
	RECHARGE_REMINDER_TITLE_VI,
	RECHARGE_REMINDER_TEXT_EN,
	RECHARGE_REMINDER_TEXT_VI,
	RECHARGE_REMINDER_IMAGE,
	RECHARGE_REMINDER_MAX_SHOW_COUNT,
	RECHARGE_REMINDER_DAYS,
	RECHARGE_REMINDER_HOURS,
	RECHARGE_REMINDER_MINUTES
}
