package com.gnv.vnm.selfcare.core.adapter.loyaltynew.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.elcom.loyalty.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-10T10:47:26.484+05:30
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://iwebservice.nms.com", name = "LoyaltyWSPortType")
@XmlSeeAlso({ObjectFactory.class, com.elcom.loyalty.ObjectFactory.class})
public interface LoyaltyWSPortType {

    @WebMethod
    @RequestWrapper(localName = "redeemPoint", targetNamespace = "http://iwebservice.nms.com", className = "com.gnv.vnm.selfcare.core.adapter.loyaltynew.ws.RedeemPoint")
    @ResponseWrapper(localName = "redeemPointResponse", targetNamespace = "http://iwebservice.nms.com", className = "com.gnv.vnm.selfcare.core.adapter.loyaltynew.ws.RedeemPointResponse")
    @WebResult(name = "out", targetNamespace = "http://iwebservice.nms.com")
    public com.elcom.loyalty.LoyaltyResp redeemPoint(
        @WebParam(name = "in0", targetNamespace = "http://iwebservice.nms.com")
        com.elcom.loyalty.LoyaltyRedeempointReq in0
    );

    @WebMethod
    @RequestWrapper(localName = "checkPoint", targetNamespace = "http://iwebservice.nms.com", className = "com.gnv.vnm.selfcare.core.adapter.loyaltynew.ws.CheckPoint")
    @ResponseWrapper(localName = "checkPointResponse", targetNamespace = "http://iwebservice.nms.com", className = "com.gnv.vnm.selfcare.core.adapter.loyaltynew.ws.CheckPointResponse")
    @WebResult(name = "out", targetNamespace = "http://iwebservice.nms.com")
    public com.elcom.loyalty.LoyaltyCheckpointResp checkPoint(
        @WebParam(name = "in0", targetNamespace = "http://iwebservice.nms.com")
        com.elcom.loyalty.LoyaltyReq in0
    );
}
