
package com.gnv.vnm.selfcare.core.adapter.loyaltynew.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.elcom.loyalty.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-10T10:47:26.412+05:30
 * Generated source version: 3.2.6
 *
 */
public final class LoyaltyWSPortType_LoyaltyWSHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://iwebservice.nms.com", "LoyaltyWS");

    private LoyaltyWSPortType_LoyaltyWSHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LoyaltyWS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        LoyaltyWS ss = new LoyaltyWS(wsdlURL, SERVICE_NAME);
        LoyaltyWSPortType port = ss.getLoyaltyWSHttpPort();

        {
        System.out.println("Invoking redeemPoint...");
        com.elcom.loyalty.LoyaltyRedeempointReq _redeemPoint_in0 = new com.elcom.loyalty.LoyaltyRedeempointReq();
        javax.xml.bind.JAXBElement<java.lang.String> _redeemPoint_in0Description = null;
        _redeemPoint_in0.setDescription(_redeemPoint_in0Description);
        javax.xml.bind.JAXBElement<java.lang.String> _redeemPoint_in0Isdn = null;
        _redeemPoint_in0.setIsdn(_redeemPoint_in0Isdn);
        javax.xml.bind.JAXBElement<java.lang.String> _redeemPoint_in0Keyword = null;
        _redeemPoint_in0.setKeyword(_redeemPoint_in0Keyword);
        javax.xml.bind.JAXBElement<java.lang.String> _redeemPoint_in0Password = null;
        _redeemPoint_in0.setPassword(_redeemPoint_in0Password);
        _redeemPoint_in0.setPoint(Long.valueOf(4146885655277544569l));
        javax.xml.bind.JAXBElement<java.lang.String> _redeemPoint_in0User = null;
        _redeemPoint_in0.setUser(_redeemPoint_in0User);
        com.elcom.loyalty.LoyaltyResp _redeemPoint__return = port.redeemPoint(_redeemPoint_in0);
        System.out.println("redeemPoint.result=" + _redeemPoint__return);


        }
        {
        ObjectFactory	obj=new ObjectFactory();
        
      
        
        System.out.println("Invoking checkPoint...");
        com.elcom.loyalty.LoyaltyReq _checkPoint_in0 = new com.elcom.loyalty.LoyaltyReq();
        _checkPoint_in0.setIsdn(obj.createLoyaltyCheckpointRespIsdn("0522939353"));
        _checkPoint_in0.setPassword(obj.createLoyaltyRedeempointReqUser("test"));
        _checkPoint_in0.setUser(obj.createLoyaltyRedeempointReqPassword("test"));
       /* javax.xml.bind.JAXBElement<java.lang.String> _checkPoint_in0Isdn = null;
        _checkPoint_in0.setIsdn(_checkPoint_in0Isdn);
        javax.xml.bind.JAXBElement<java.lang.String> _checkPoint_in0Password = null;
        _checkPoint_in0.setPassword(_checkPoint_in0Password);
        javax.xml.bind.JAXBElement<java.lang.String> _checkPoint_in0User = null;
        _checkPoint_in0.setUser(_checkPoint_in0User);*/
        com.elcom.loyalty.LoyaltyCheckpointResp _checkPoint__return = port.checkPoint(_checkPoint_in0);
        System.out.println("checkPoint.result=" + _checkPoint__return.getPoint());


        }

        System.exit(0);
    }

}
