
   ALTER SEQUENCE  SCUSER.CONTENT_CATMD_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.CONTENT_CATV2_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.CONTENT_V2_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.PCAT_V2_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.PGROUP_MD_SEQ  INCREMENT BY 1 MINVALUE 321;

   ALTER SEQUENCE  SCUSER.PGROUP_SEQ  INCREMENT BY 1 MINVALUE 61;

   ALTER SEQUENCE  SCUSER.PRODCAT_MD_SEQ  INCREMENT BY 1 MINVALUE 61;

   ALTER SEQUENCE  SCUSER.PRODUCT_MD_V2_SEQ  INCREMENT BY 1 MINVALUE 221;

   ALTER SEQUENCE  SCUSER.PRODUCT_V2_SEQ  INCREMENT BY 1 MINVALUE 81;

   ALTER SEQUENCE  SCUSER.TOPUP_TYPE_SEQ  INCREMENT BY 1 MINVALUE 81;

   ALTER SEQUENCE  SCUSER.PUSHED_CAMP_SEQ  INCREMENT BY 1 MINVALUE 41;

   ALTER SEQUENCE  SCUSER.STORE_SEQ  INCREMENT BY 1 MINVALUE 384;

   ALTER SEQUENCE  SCUSER.TOKEN_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.CATEGORY_NAME_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.HIBERNATE_SEQUENCE  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.APPS_BANNER_SEQ  INCREMENT BY 1 MINVALUE 41;

   ALTER SEQUENCE  SCUSER.MOVIE_BANNER_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.MUSIC_BANNER_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.HIDDEN_PROD_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.GAME_BANNER_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.COMMON_METADATA_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.PPM_SEQ  INCREMENT BY 1 MINVALUE 61;

   ALTER SEQUENCE  SCUSER.APP_CONFIG_SEQ  INCREMENT BY 1 MINVALUE 301;

   ALTER SEQUENCE  SCUSER.BACKEND_REQLOG_SEQ  INCREMENT BY 1 MINVALUE 188501;

   ALTER SEQUENCE  SCUSER.CONTENT_MD_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.CONTENT_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.CONTENT_SUBS_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.LOGIN_HISTORY_SEQ  INCREMENT BY 1 MINVALUE 1741;

   ALTER SEQUENCE  SCUSER.OTP_SEQ  INCREMENT BY 1 MINVALUE 501;

   ALTER SEQUENCE  SCUSER.PROD_CAT_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.PRODUCT_MD_SEQ  INCREMENT BY 1 MINVALUE 2003;

   ALTER SEQUENCE  SCUSER.PRODUCT_SEQ  INCREMENT BY 1 MINVALUE 223;

   ALTER SEQUENCE  SCUSER.PRODUCT_SUBS_SEQ  INCREMENT BY 1 MINVALUE 201;

   ALTER SEQUENCE  SCUSER.SUBSCRIBER_REG_SEQ  INCREMENT BY 1 MINVALUE 121;

   ALTER SEQUENCE  SCUSER.SUBSCRIBER_SEQ  INCREMENT BY 1 MINVALUE 381;

   ALTER SEQUENCE  SCUSER.TOPUP_HIST_SEQ  INCREMENT BY 1 MINVALUE 761;

   ALTER SEQUENCE  SCUSER.TRX_HIST_SEQ  INCREMENT BY 1 MINVALUE 861;

   ALTER SEQUENCE  SCUSER.PROMOTED_PROD_SEQ  INCREMENT BY 1 MINVALUE 41;

   ALTER SEQUENCE  SCUSER.GAME_CAT_SEQ  INCREMENT BY 1 MINVALUE 81;

   ALTER SEQUENCE  SCUSER.CONTENT_CAT_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.GAME_CATMD_SEQ  INCREMENT BY 1 MINVALUE 41;

   ALTER SEQUENCE  SCUSER.GAME_MD_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.GAME_SEQ  INCREMENT BY 1 MINVALUE 7621;

   ALTER SEQUENCE  SCUSER.MOVIE_CAT_SEQ  INCREMENT BY 1 MINVALUE 81;

   ALTER SEQUENCE  SCUSER.MOVIE_CATMD_SEQ  INCREMENT BY 1 MINVALUE 41;

   ALTER SEQUENCE  SCUSER.MOVIE_MD_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.MOVIE_SEQ  INCREMENT BY 1 MINVALUE 3388;

   ALTER SEQUENCE  SCUSER.MUSIC_CAT_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.MUSIC_CATMD_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.MUSIC_MD_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.MUSIC_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.PCAT_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.LMS_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.MGM_SEQ  INCREMENT BY 1 MINVALUE 81;

   ALTER SEQUENCE  SCUSER.PURCHASE_NOTIF_SEQ  INCREMENT BY 1 MINVALUE 241;

   ALTER SEQUENCE  SCUSER.BANK_SEQ  INCREMENT BY 1 MINVALUE 61;

   ALTER SEQUENCE  SCUSER.PRODUCT_SUBS_V2_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.PROMOTED_PROD_V2_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.TRX_HIST_V2_SEQ  INCREMENT BY 1 MINVALUE 141;

   ALTER SEQUENCE  SCUSER.HIDDEN_PROD_GROUP_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.AVATAR_SEQ  INCREMENT BY 1 MINVALUE 361;

   ALTER SEQUENCE  SCUSER.PAY_HIST_SEQ  INCREMENT BY 1 MINVALUE 1021;

   ALTER SEQUENCE  SCUSER.APPS_MD_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.APPS_SEQ  INCREMENT BY 1 MINVALUE 7121;

   ALTER SEQUENCE  SCUSER.LOYALTYKEYWORD_SEQ  INCREMENT BY 1 MINVALUE 1;

   ALTER SEQUENCE  SCUSER.RTBS_BALANCE_MAP_SEQ  INCREMENT BY 1 MINVALUE 21;

   ALTER SEQUENCE  SCUSER.APPS_CAT_SEQ  INCREMENT BY 1 MINVALUE 201;

   ALTER SEQUENCE  SCUSER.APPS_CATMD_SEQ  INCREMENT BY 1 MINVALUE 61;

   ALTER SEQUENCE  SCUSER.COS_SEQ  INCREMENT BY 1 MINVALUE 301;

   ALTER SEQUENCE  SCUSER.BALANCE_MAP_SEQ  INCREMENT BY 1 MINVALUE 60;


ALTER SEQUENCE  SCUSER.SUBSCRIBER_SEQ  INCREMENT BY 1 MINVALUE 75331865;


   CREATE SEQUENCE  "SCUSER"."SUBSCRIBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 381 START WITH 75331865 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
