insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '686868', 'Vietcombank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970436','Vietcombank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970407', 'Techcombank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '889988', 'Techcombank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '888899', 'Techcombank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970441', 'VIBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '180909', 'VIBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '180906', 'VIBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '707070', 'EximBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970431', 'EximBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '193939', 'MB (NH Quân Đội)');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970422', 'MB (NH Quân Đội)');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '6201', 'Vietinbank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970415', 'Vietinbank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970420', 'HD Bank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970437', 'HD Bank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970416', 'ACB (NH Á Châu)');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970403', 'Sacombank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '818188', 'NCB (Ngân hàng quốc dân)');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970419', 'NCB (Ngân hàng quốc dân)');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970426', 'Maritimebank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970427', 'VietABank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970432', 'VPBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '981957', 'VPBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970408', 'GPBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970414', 'Oceanbank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970409', 'NASB (NH Bắc Á)');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970448', 'OCB (NH Phương Đông)');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '1792', 'DongAbank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970406', 'DongAbank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970425', 'ABBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '191919', 'ABBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970423', 'TPB - NH Tiên Phong');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970449', 'LPB - NH Bưu điện Liên Việt');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970443', 'SHB - NH TMCP Sài Gòn – Hà Nội');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970438', 'BVB - NH TMCP Bảo Việt');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970418', 'BIDV');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '668899', 'BIDV');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970405', 'Agribank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970468', 'Seabank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970440', 'Seabank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970429', 'SCB');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970452', 'KLB');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970421', 'VRB');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970412', 'PVCom');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970439', 'VID-Public');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970428', 'Nam Á');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970430', 'PGBank');
insert into bank(id, create_timestamp, created_by, last_modified_timestamp, last_modified_by, code, name) values (bank_seq.nextval, sysdate, 'system', sysdate, 'system', '970400', 'Smartlink Card');
