insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 1, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 1, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 1, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 2, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 2, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 2, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 3, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 3, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 3, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 4, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 4, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 4, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 5, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 5, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 5, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 6, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 6, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 6, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 7, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 7, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 7, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 8, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 8, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 8, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 9, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 9, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 9, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 10, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 10, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 10, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 11, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 11, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 11, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 12, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 12, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 12, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 13, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 13, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 13, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 14, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 14, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 14, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 15, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 15, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 15, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 16, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 16, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 16, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 17, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 17, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 17, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 18, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 18, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 18, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 19, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 19, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 19, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 20, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 20, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 20, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 21, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 21, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 21, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 22, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 22, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 22, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_320x200', 'IMGSIZE_CUSTOM_320x200', 23, '/prd/dummy_329x200.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_400x300', 'IMGSIZE_CUSTOM_400x300', 23, '/prd/dummy_400x300.png');
insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value) values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'IMGSIZE_CUSTOM_1024x600', 'IMGSIZE_CUSTOM_1024x600', 23, '/prd/dummy_1024x600.png');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value)
    values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'QUOTA', 'Quota', (select id from product where code = '125528'), '1GB');

insert into product_metadata(id, create_timestamp, created_by, last_modified_by, last_modified_timestamp, name, description, product_id, value)
        values(product_md_seq.nextval, sysdate, 'system', 'system', sysdate, 'QUOTA', 'Quota', (select id from product where code = '125528'), '1GB');
