package com.gnv.vnm.selfcare.core.adapter.loyalty.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-02-02T16:11:46.310+07:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://iwebservice.nms.com", name = "loyaltyWSPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface LoyaltyWSPortType {

    @WebMethod
    @RequestWrapper(localName = "redeemPoint", targetNamespace = "http://iwebservice.nms.com", className = "com.gnv.vnm.selfcare.core.adapter.loyalty.ws.RedeemPoint")
    @ResponseWrapper(localName = "redeemPointResponse", targetNamespace = "http://iwebservice.nms.com", className = "com.gnv.vnm.selfcare.core.adapter.loyalty.ws.RedeemPointResponse")
    @WebResult(name = "out", targetNamespace = "http://iwebservice.nms.com")
    public com.gnv.vnm.selfcare.core.adapter.loyalty.ws.LoyaltyResp redeemPoint(
        @WebParam(name = "in0", targetNamespace = "http://iwebservice.nms.com")
        com.gnv.vnm.selfcare.core.adapter.loyalty.ws.LoyaltyRedeempointReq in0
    );

    @WebMethod
    @RequestWrapper(localName = "checkPoint", targetNamespace = "http://iwebservice.nms.com", className = "com.gnv.vnm.selfcare.core.adapter.loyalty.ws.CheckPoint")
    @ResponseWrapper(localName = "checkPointResponse", targetNamespace = "http://iwebservice.nms.com", className = "com.gnv.vnm.selfcare.core.adapter.loyalty.ws.CheckPointResponse")
    @WebResult(name = "out", targetNamespace = "http://iwebservice.nms.com")
    public com.gnv.vnm.selfcare.core.adapter.loyalty.ws.LoyaltyCheckpointResp checkPoint(
        @WebParam(name = "in0", targetNamespace = "http://iwebservice.nms.com")
        com.gnv.vnm.selfcare.core.adapter.loyalty.ws.LoyaltyReq in0
    );
}
