
package com.gnv.vnm.selfcare.core.adapter.loyalty.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-02-02T16:11:46.265+07:00
 * Generated source version: 3.1.10
 * 
 */
public final class LoyaltyWSPortType_LoyaltyWSHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://iwebservice.nms.com", "loyaltyWS");

    private LoyaltyWSPortType_LoyaltyWSHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LoyaltyWS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LoyaltyWS ss = new LoyaltyWS(wsdlURL, SERVICE_NAME);
        LoyaltyWSPortType port = ss.getLoyaltyWSHttpPort();  
        
        {
        System.out.println("Invoking redeemPoint...");
        com.gnv.vnm.selfcare.core.adapter.loyalty.ws.LoyaltyRedeempointReq _redeemPoint_in0 = null;
        com.gnv.vnm.selfcare.core.adapter.loyalty.ws.LoyaltyResp _redeemPoint__return = port.redeemPoint(_redeemPoint_in0);
        System.out.println("redeemPoint.result=" + _redeemPoint__return);


        }
        {
        System.out.println("Invoking checkPoint...");
        com.gnv.vnm.selfcare.core.adapter.loyalty.ws.LoyaltyReq _checkPoint_in0 = null;
        com.gnv.vnm.selfcare.core.adapter.loyalty.ws.LoyaltyCheckpointResp _checkPoint__return = port.checkPoint(_checkPoint_in0);
        System.out.println("checkPoint.result=" + _checkPoint__return);


        }

        System.exit(0);
    }

}
