/**
 * 
 */
package com.gnv.vnm.selfcare.core.enums;

/**
 * @author nandipinto
 *
 */
public enum SelfPackageConfigKey {

	STEP_PER_ITEM_VOICE,
	STEP_PER_ITEM_SMS,
	STEP_PER_ITEM_DATA,
	MULTIPLIER_VND,
	DATA_DAILY_INCR_VALUE,
	DATA_DAILY_MAX_VALUE,
	DATA_MONTHLY_INCR_VALUE,
	DATA_MONTHLY_MAX_VALUE,
	DATA_WEEKLY_INCR_VALUE,
	DATA_WEEKLY_MAX_VALUE,
	PACKAGE_ID,
	SMS_DAILY_INCR_VALUE,
	SMS_DAILY_MAX_VALUE,
	SMS_MONTHLY_INCR_VALUE,
	SMS_MONTHLY_MAX_VALUE,
	SMS_WEEKLY_INCR_VALUE,
	SMS_WEEKLY_MAX_VALUE,
	VOICE_DAILY_INCR_VALUE,
	VOICE_DAILY_MAX_VALUE,
	VOICE_MONTHLY_INCR_VALUE,
	VOICE_MONTHLY_MAX_VALUE,
	VOICE_WEEKLY_INCR_VALUE,
	VOICE_WEEKLY_MAX_VALUE
	
	
}
