package com.gnv.vnm.selfcare.core.adapter.upcc.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.8
 * 2017-01-11T17:01:08.020+07:00
 * Generated source version: 2.3.8
 * 
 */
@WebService(targetNamespace = "rm:soap", name = "ScfPccSoapServiceEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ScfPccSoapServiceEndpoint {

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO addSubscriberAlias(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberAliasParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriberAlias(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberAliasParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getGroupMember(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaAttrVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriberCustomLevel(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberCustomLevelParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO delSubscriber(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriberAllInf(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberAllInfParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO unSubscribeAccumulation(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberAccumulationParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO subscribeService(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriptionParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriberAllServicePackage(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO addSubscriber(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO rechargeSubscriberService(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberRechargedServiceParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriber(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO subscribeServicePacket(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriptionParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO unSubscribeServicePacket(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriptionParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO rechargeSubscriberQuota(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberRechargedQuotaParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO updateSubscriberQuota(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberQuotaParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO updateSubscriberCustomLevel(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberCustomLevelParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO setSubscriberShareQuota(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberShareQuotaParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriberSpecQuota(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberQuotaParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO updateSubscriber(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getGroupMemberList(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaAttrVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriberAllService(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO updateSubscribedServicePackage(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberServicePackageParaVO inPara
    );

    @WebMethod(operationName = "LGI")
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO lgi(
        @WebParam(partName = "inPara", name = "inPara")
        SLoginParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO unSubscribeServicePackage(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberServicePackageParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO updateSubSubscription(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriptionParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriberAccumulation(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberAccumulationParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO addGroupMember(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberGroupMemberQuotaParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriberAllServicePacket(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO setSubscriberAttribute(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaAttrVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO clearAccumulation(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberClearAccumulationParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO unSubscribeService(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriptionParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO updateSubscriberAlias(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberAliasParaVO inPara
    );

    @WebMethod(operationName = "LGO")
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO lgo(
        @WebParam(partName = "inPara", name = "inPara")
        SLogoutParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO delSubscriberAlias(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberAliasParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO delGroupMember(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaAttrVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO updateGroupMember(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberGroupMemberQuotaParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSecondSubscriber(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaAttrVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriberAccount(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO updateSubscriberAccount(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberAccountParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO getSubscriberAllQuota(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberQuotaParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO subscribeServicePackage(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberServicePackageParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO resetSubscriberQuota(
        @WebParam(partName = "inPara", name = "inPara")
        SInASubscribeResetQuotaParaVO inPara
    );

    @WebMethod
    @WebResult(name = "result", targetNamespace = "rm:soap", partName = "result")
    public SReturnVO subscribeAccumulation(
        @WebParam(partName = "inPara", name = "inPara")
        SInSubscriberAccumulationParaVO inPara
    );
}
