
package com.gnv.vnm.selfcare.core.adapter.upcc.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.3.8 2017-01-11T17:01:07.947+07:00
 * Generated source version: 2.3.8
 * 
 */
public final class ScfPccSoapServiceEndpoint_ScfPccSoapServiceEndpointPort_Client {

	private static final QName SERVICE_NAME = new QName("rm:soap", "ScfMobileSoap");

	private ScfPccSoapServiceEndpoint_ScfPccSoapServiceEndpointPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = ScfMobileSoap.WSDL_LOCATION;
		if (args.length > 0) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		ScfMobileSoap ss = new ScfMobileSoap(wsdlURL, SERVICE_NAME);
		ScfPccSoapServiceEndpoint port = ss.getScfPccSoapServiceEndpointPort();

		{
			System.out.println("Invoking addSubscriberAlias...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberAliasParaVO _addSubscriberAlias_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _addSubscriberAlias__return = port
					.addSubscriberAlias(_addSubscriberAlias_inPara);
			System.out.println("addSubscriberAlias.result=" + _addSubscriberAlias__return);

		}
		{
			System.out.println("Invoking getSubscriberAlias...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberAliasParaVO _getSubscriberAlias_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriberAlias__return = port
					.getSubscriberAlias(_getSubscriberAlias_inPara);
			System.out.println("getSubscriberAlias.result=" + _getSubscriberAlias__return);

		}
		{
			System.out.println("Invoking getGroupMember...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaAttrVO _getGroupMember_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getGroupMember__return = port
					.getGroupMember(_getGroupMember_inPara);
			System.out.println("getGroupMember.result=" + _getGroupMember__return);

		}
		{
			System.out.println("Invoking getSubscriberCustomLevel...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberCustomLevelParaVO _getSubscriberCustomLevel_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriberCustomLevel__return = port
					.getSubscriberCustomLevel(_getSubscriberCustomLevel_inPara);
			System.out.println("getSubscriberCustomLevel.result=" + _getSubscriberCustomLevel__return);

		}
		{
			System.out.println("Invoking delSubscriber...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaVO _delSubscriber_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _delSubscriber__return = port
					.delSubscriber(_delSubscriber_inPara);
			System.out.println("delSubscriber.result=" + _delSubscriber__return);

		}
		{
			System.out.println("Invoking getSubscriberAllInf...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberAllInfParaVO _getSubscriberAllInf_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriberAllInf__return = port
					.getSubscriberAllInf(_getSubscriberAllInf_inPara);
			System.out.println("getSubscriberAllInf.result=" + _getSubscriberAllInf__return);

		}
		{
			System.out.println("Invoking unSubscribeAccumulation...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberAccumulationParaVO _unSubscribeAccumulation_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _unSubscribeAccumulation__return = port
					.unSubscribeAccumulation(_unSubscribeAccumulation_inPara);
			System.out.println("unSubscribeAccumulation.result=" + _unSubscribeAccumulation__return);

		}
		{
			System.out.println("Invoking subscribeService...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriptionParaVO _subscribeService_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _subscribeService__return = port
					.subscribeService(_subscribeService_inPara);
			System.out.println("subscribeService.result=" + _subscribeService__return);

		}
		{
			System.out.println("Invoking getSubscriberAllServicePackage...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaVO _getSubscriberAllServicePackage_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriberAllServicePackage__return = port
					.getSubscriberAllServicePackage(_getSubscriberAllServicePackage_inPara);
			System.out.println("getSubscriberAllServicePackage.result=" + _getSubscriberAllServicePackage__return);

		}
		{
			System.out.println("Invoking addSubscriber...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaVO _addSubscriber_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _addSubscriber__return = port
					.addSubscriber(_addSubscriber_inPara);
			System.out.println("addSubscriber.result=" + _addSubscriber__return);

		}
		{
			System.out.println("Invoking rechargeSubscriberService...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberRechargedServiceParaVO _rechargeSubscriberService_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _rechargeSubscriberService__return = port
					.rechargeSubscriberService(_rechargeSubscriberService_inPara);
			System.out.println("rechargeSubscriberService.result=" + _rechargeSubscriberService__return);

		}
		{
			System.out.println("Invoking getSubscriber...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaVO _getSubscriber_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriber__return = port
					.getSubscriber(_getSubscriber_inPara);
			System.out.println("getSubscriber.result=" + _getSubscriber__return);

		}
		{
			System.out.println("Invoking subscribeServicePacket...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriptionParaVO _subscribeServicePacket_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _subscribeServicePacket__return = port
					.subscribeServicePacket(_subscribeServicePacket_inPara);
			System.out.println("subscribeServicePacket.result=" + _subscribeServicePacket__return);

		}
		{
			System.out.println("Invoking unSubscribeServicePacket...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriptionParaVO _unSubscribeServicePacket_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _unSubscribeServicePacket__return = port
					.unSubscribeServicePacket(_unSubscribeServicePacket_inPara);
			System.out.println("unSubscribeServicePacket.result=" + _unSubscribeServicePacket__return);

		}
		{
			System.out.println("Invoking rechargeSubscriberQuota...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberRechargedQuotaParaVO _rechargeSubscriberQuota_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _rechargeSubscriberQuota__return = port
					.rechargeSubscriberQuota(_rechargeSubscriberQuota_inPara);
			System.out.println("rechargeSubscriberQuota.result=" + _rechargeSubscriberQuota__return);

		}
		{
			System.out.println("Invoking updateSubscriberQuota...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberQuotaParaVO _updateSubscriberQuota_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _updateSubscriberQuota__return = port
					.updateSubscriberQuota(_updateSubscriberQuota_inPara);
			System.out.println("updateSubscriberQuota.result=" + _updateSubscriberQuota__return);

		}
		{
			System.out.println("Invoking updateSubscriberCustomLevel...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberCustomLevelParaVO _updateSubscriberCustomLevel_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _updateSubscriberCustomLevel__return = port
					.updateSubscriberCustomLevel(_updateSubscriberCustomLevel_inPara);
			System.out.println("updateSubscriberCustomLevel.result=" + _updateSubscriberCustomLevel__return);

		}
		{
			System.out.println("Invoking setSubscriberShareQuota...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberShareQuotaParaVO _setSubscriberShareQuota_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _setSubscriberShareQuota__return = port
					.setSubscriberShareQuota(_setSubscriberShareQuota_inPara);
			System.out.println("setSubscriberShareQuota.result=" + _setSubscriberShareQuota__return);

		}
		{
			System.out.println("Invoking getSubscriberSpecQuota...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberQuotaParaVO _getSubscriberSpecQuota_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriberSpecQuota__return = port
					.getSubscriberSpecQuota(_getSubscriberSpecQuota_inPara);
			System.out.println("getSubscriberSpecQuota.result=" + _getSubscriberSpecQuota__return);

		}
		{
			System.out.println("Invoking updateSubscriber...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaVO _updateSubscriber_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _updateSubscriber__return = port
					.updateSubscriber(_updateSubscriber_inPara);
			System.out.println("updateSubscriber.result=" + _updateSubscriber__return);

		}
		{
			System.out.println("Invoking getGroupMemberList...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaAttrVO _getGroupMemberList_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getGroupMemberList__return = port
					.getGroupMemberList(_getGroupMemberList_inPara);
			System.out.println("getGroupMemberList.result=" + _getGroupMemberList__return);

		}
		{
			System.out.println("Invoking getSubscriberAllService...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaVO _getSubscriberAllService_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriberAllService__return = port
					.getSubscriberAllService(_getSubscriberAllService_inPara);
			System.out.println("getSubscriberAllService.result=" + _getSubscriberAllService__return);

		}
		{
			System.out.println("Invoking updateSubscribedServicePackage...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberServicePackageParaVO _updateSubscribedServicePackage_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _updateSubscribedServicePackage__return = port
					.updateSubscribedServicePackage(_updateSubscribedServicePackage_inPara);
			System.out.println("updateSubscribedServicePackage.result=" + _updateSubscribedServicePackage__return);

		}
		{
			System.out.println("Invoking lgi...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SLoginParaVO _lgi_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _lgi__return = port.lgi(_lgi_inPara);
			System.out.println("lgi.result=" + _lgi__return);

		}
		{
			System.out.println("Invoking unSubscribeServicePackage...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberServicePackageParaVO _unSubscribeServicePackage_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _unSubscribeServicePackage__return = port
					.unSubscribeServicePackage(_unSubscribeServicePackage_inPara);
			System.out.println("unSubscribeServicePackage.result=" + _unSubscribeServicePackage__return);

		}
		{
			System.out.println("Invoking updateSubSubscription...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriptionParaVO _updateSubSubscription_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _updateSubSubscription__return = port
					.updateSubSubscription(_updateSubSubscription_inPara);
			System.out.println("updateSubSubscription.result=" + _updateSubSubscription__return);

		}
		{
			System.out.println("Invoking getSubscriberAccumulation...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberAccumulationParaVO _getSubscriberAccumulation_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriberAccumulation__return = port
					.getSubscriberAccumulation(_getSubscriberAccumulation_inPara);
			System.out.println("getSubscriberAccumulation.result=" + _getSubscriberAccumulation__return);

		}
		{
			System.out.println("Invoking addGroupMember...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberGroupMemberQuotaParaVO _addGroupMember_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _addGroupMember__return = port
					.addGroupMember(_addGroupMember_inPara);
			System.out.println("addGroupMember.result=" + _addGroupMember__return);

		}
		{
			System.out.println("Invoking getSubscriberAllServicePacket...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaVO _getSubscriberAllServicePacket_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriberAllServicePacket__return = port
					.getSubscriberAllServicePacket(_getSubscriberAllServicePacket_inPara);
			System.out.println("getSubscriberAllServicePacket.result=" + _getSubscriberAllServicePacket__return);

		}
		{
			System.out.println("Invoking setSubscriberAttribute...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaAttrVO _setSubscriberAttribute_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _setSubscriberAttribute__return = port
					.setSubscriberAttribute(_setSubscriberAttribute_inPara);
			System.out.println("setSubscriberAttribute.result=" + _setSubscriberAttribute__return);

		}
		{
			System.out.println("Invoking clearAccumulation...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberClearAccumulationParaVO _clearAccumulation_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _clearAccumulation__return = port
					.clearAccumulation(_clearAccumulation_inPara);
			System.out.println("clearAccumulation.result=" + _clearAccumulation__return);

		}
		{
			System.out.println("Invoking unSubscribeService...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriptionParaVO _unSubscribeService_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _unSubscribeService__return = port
					.unSubscribeService(_unSubscribeService_inPara);
			System.out.println("unSubscribeService.result=" + _unSubscribeService__return);

		}
		{
			System.out.println("Invoking updateSubscriberAlias...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberAliasParaVO _updateSubscriberAlias_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _updateSubscriberAlias__return = port
					.updateSubscriberAlias(_updateSubscriberAlias_inPara);
			System.out.println("updateSubscriberAlias.result=" + _updateSubscriberAlias__return);

		}
		{
			System.out.println("Invoking lgo...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SLogoutParaVO _lgo_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _lgo__return = port.lgo(_lgo_inPara);
			System.out.println("lgo.result=" + _lgo__return);

		}
		{
			System.out.println("Invoking delSubscriberAlias...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberAliasParaVO _delSubscriberAlias_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _delSubscriberAlias__return = port
					.delSubscriberAlias(_delSubscriberAlias_inPara);
			System.out.println("delSubscriberAlias.result=" + _delSubscriberAlias__return);

		}
		{
			System.out.println("Invoking delGroupMember...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaAttrVO _delGroupMember_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _delGroupMember__return = port
					.delGroupMember(_delGroupMember_inPara);
			System.out.println("delGroupMember.result=" + _delGroupMember__return);

		}
		{
			System.out.println("Invoking updateGroupMember...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberGroupMemberQuotaParaVO _updateGroupMember_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _updateGroupMember__return = port
					.updateGroupMember(_updateGroupMember_inPara);
			System.out.println("updateGroupMember.result=" + _updateGroupMember__return);

		}
		{
			System.out.println("Invoking getSecondSubscriber...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaAttrVO _getSecondSubscriber_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSecondSubscriber__return = port
					.getSecondSubscriber(_getSecondSubscriber_inPara);
			System.out.println("getSecondSubscriber.result=" + _getSecondSubscriber__return);

		}
		{
			System.out.println("Invoking getSubscriberAccount...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberParaVO _getSubscriberAccount_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriberAccount__return = port
					.getSubscriberAccount(_getSubscriberAccount_inPara);
			System.out.println("getSubscriberAccount.result=" + _getSubscriberAccount__return);

		}
		{
			System.out.println("Invoking updateSubscriberAccount...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberAccountParaVO _updateSubscriberAccount_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _updateSubscriberAccount__return = port
					.updateSubscriberAccount(_updateSubscriberAccount_inPara);
			System.out.println("updateSubscriberAccount.result=" + _updateSubscriberAccount__return);

		}
		{
			System.out.println("Invoking getSubscriberAllQuota...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberQuotaParaVO _getSubscriberAllQuota_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _getSubscriberAllQuota__return = port
					.getSubscriberAllQuota(_getSubscriberAllQuota_inPara);
			System.out.println("getSubscriberAllQuota.result=" + _getSubscriberAllQuota__return);

		}
		{
			System.out.println("Invoking subscribeServicePackage...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberServicePackageParaVO _subscribeServicePackage_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _subscribeServicePackage__return = port
					.subscribeServicePackage(_subscribeServicePackage_inPara);
			System.out.println("subscribeServicePackage.result=" + _subscribeServicePackage__return);

		}
		{
			System.out.println("Invoking resetSubscriberQuota...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInASubscribeResetQuotaParaVO _resetSubscriberQuota_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _resetSubscriberQuota__return = port
					.resetSubscriberQuota(_resetSubscriberQuota_inPara);
			System.out.println("resetSubscriberQuota.result=" + _resetSubscriberQuota__return);

		}
		{
			System.out.println("Invoking subscribeAccumulation...");
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SInSubscriberAccumulationParaVO _subscribeAccumulation_inPara = null;
			com.gnv.vnm.selfcare.core.adapter.upcc.ws.SReturnVO _subscribeAccumulation__return = port
					.subscribeAccumulation(_subscribeAccumulation_inPara);
			System.out.println("subscribeAccumulation.result=" + _subscribeAccumulation__return);

		}

		System.exit(0);
	}

}
