package com.gnv.vnm.selfcare.core.adapter.vasman.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-21T11:49:58.962+07:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://vasman.elcom.com", name = "WSVasnewPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface WSVasnewPortType {

    @WebMethod
    @RequestWrapper(localName = "dynamicServiceProvisioning", targetNamespace = "http://vasman.elcom.com", className = "com.gnv.vnm.selfcare.core.adapter.vasman.ws.DynamicServiceProvisioning")
    @ResponseWrapper(localName = "dynamicServiceProvisioningResponse", targetNamespace = "http://vasman.elcom.com", className = "com.gnv.vnm.selfcare.core.adapter.vasman.ws.DynamicServiceProvisioningResponse")
    @WebResult(name = "out", targetNamespace = "http://vasman.elcom.com")
    public com.gnv.vnm.selfcare.core.adapter.vasman.ws.ProvisioningResp dynamicServiceProvisioning(
        @WebParam(name = "in0", targetNamespace = "http://vasman.elcom.com")
        com.gnv.vnm.selfcare.core.adapter.vasman.ws.ProvisioningDynamicServiceReq in0
    );

    @WebMethod(operationName = "ProvisioningWithCampaign")
    @RequestWrapper(localName = "ProvisioningWithCampaign", targetNamespace = "http://vasman.elcom.com", className = "com.gnv.vnm.selfcare.core.adapter.vasman.ws.ProvisioningWithCampaign")
    @ResponseWrapper(localName = "ProvisioningWithCampaignResponse", targetNamespace = "http://vasman.elcom.com", className = "com.gnv.vnm.selfcare.core.adapter.vasman.ws.ProvisioningWithCampaignResponse")
    @WebResult(name = "out", targetNamespace = "http://vasman.elcom.com")
    public com.gnv.vnm.selfcare.core.adapter.vasman.ws.ProvisioningResp provisioningWithCampaign(
        @WebParam(name = "in0", targetNamespace = "http://vasman.elcom.com")
        com.gnv.vnm.selfcare.core.adapter.vasman.ws.ProvisioningCampaignReq in0
    );

    @WebMethod
    @RequestWrapper(localName = "terminateAllVas", targetNamespace = "http://vasman.elcom.com", className = "com.gnv.vnm.selfcare.core.adapter.vasman.ws.TerminateAllVas")
    @ResponseWrapper(localName = "terminateAllVasResponse", targetNamespace = "http://vasman.elcom.com", className = "com.gnv.vnm.selfcare.core.adapter.vasman.ws.TerminateAllVasResponse")
    @WebResult(name = "out", targetNamespace = "http://vasman.elcom.com")
    public com.gnv.vnm.selfcare.core.adapter.vasman.ws.TerminalAllVasResp terminateAllVas(
        @WebParam(name = "in0", targetNamespace = "http://vasman.elcom.com")
        com.gnv.vnm.selfcare.core.adapter.vasman.ws.CheckAllVasStatusReq in0
    );

    @WebMethod(operationName = "MemberManagement")
    @RequestWrapper(localName = "MemberManagement", targetNamespace = "http://vasman.elcom.com", className = "com.gnv.vnm.selfcare.core.adapter.vasman.ws.MemberManagement")
    @ResponseWrapper(localName = "MemberManagementResponse", targetNamespace = "http://vasman.elcom.com", className = "com.gnv.vnm.selfcare.core.adapter.vasman.ws.MemberManagementResponse")
    @WebResult(name = "out", targetNamespace = "http://vasman.elcom.com")
    public com.gnv.vnm.selfcare.core.adapter.vasman.ws.MemberManagementResp memberManagement(
        @WebParam(name = "in0", targetNamespace = "http://vasman.elcom.com")
        com.gnv.vnm.selfcare.core.adapter.vasman.ws.MemberManagementReq in0
    );

    @WebMethod(operationName = "VasDetail")
    @RequestWrapper(localName = "VasDetail", targetNamespace = "http://vasman.elcom.com", className = "com.gnv.vnm.selfcare.core.adapter.vasman.ws.VasDetail")
    @ResponseWrapper(localName = "VasDetailResponse", targetNamespace = "http://vasman.elcom.com", className = "com.gnv.vnm.selfcare.core.adapter.vasman.ws.VasDetailResponse")
    @WebResult(name = "out", targetNamespace = "http://vasman.elcom.com")
    public com.gnv.vnm.selfcare.core.adapter.vasman.ws.VasDetailResp vasDetail(
        @WebParam(name = "in0", targetNamespace = "http://vasman.elcom.com")
        com.gnv.vnm.selfcare.core.adapter.vasman.ws.CheckVasStatusReq in0
    );
}
