package com.gnv.vnm.selfcare.core.adapter.vasman.ws;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-21T11:49:58.967+07:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "WSVasnew", 
                  wsdlLocation = "classpath:wsdl/WSVasnew.wsdl",
                  targetNamespace = "http://vasman.elcom.com") 
public class WSVasnew extends Service {

    public final static URL WSDL_LOCATION;

//    public final static QName SERVICE = new QName("http://vasman.elcom.com", "WSVasnew");
    public final static QName SERVICE = new QName("http://vasman.elcom.com", "WSVasnew");

    public final static QName WSVasnewHttpPort = new QName("http://vasman.elcom.com", "WSVasnewHttpPort");
    
    static {
        URL url = WSVasnew.class.getClassLoader().getResource("wsdl/WSVasnew.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(WSVasnew.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/WSVasnew.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public WSVasnew(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSVasnew(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSVasnew() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSVasnew(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSVasnew(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSVasnew(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WSVasnewPortType
     */
    @WebEndpoint(name = "WSVasnewHttpPort")
    public WSVasnewPortType getWSVasnewHttpPort() {
        return super.getPort(WSVasnewHttpPort, WSVasnewPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSVasnewPortType
     */
    @WebEndpoint(name = "WSVasnewHttpPort")
    public WSVasnewPortType getWSVasnewHttpPort(WebServiceFeature... features) {
        return super.getPort(WSVasnewHttpPort, WSVasnewPortType.class, features);
    }

}
