package com.gnv.vnm.selfcare.core.adapter.tibco;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-07-11T14:02:32.761+07:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "Selfcare_Inbound", 
                  wsdlLocation = "classpath:wsdl/Tibco.wsdl",
                  targetNamespace = "http://xmlns.example.com/1491473061728") 
public class SelfcareInboundService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.example.com/1491473061728", "Selfcare_Inbound");
    public final static QName SelfcareInbound = new QName("http://xmlns.example.com/1491473061728", "SelfcareInbound");
    static {
        URL url = SelfcareInboundService.class.getClassLoader().getResource("wsdl/Tibco.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SelfcareInboundService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Tibco.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public SelfcareInboundService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SelfcareInboundService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SelfcareInboundService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SelfcareInboundService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SelfcareInboundService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SelfcareInboundService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SelfcareInbound
     */
    @WebEndpoint(name = "SelfcareInbound")
    public SelfcareInbound getSelfcareInbound() {
        return super.getPort(SelfcareInbound, SelfcareInbound.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SelfcareInbound
     */
    @WebEndpoint(name = "SelfcareInbound")
    public SelfcareInbound getSelfcareInbound(WebServiceFeature... features) {
        return super.getPort(SelfcareInbound, SelfcareInbound.class, features);
    }

}
