/**
 * RTBSActionTypes.java
 */
package com.gnv.vnm.selfcare.core.adapter.rtbs;

/**
 * @author nandipinto
 *
 */
public enum RTBSActionTypes {

	VIEW_SUBSCRIBER, VIEW_LOCATION, VIEW_ACTIVITY_HISTORY, VIEW_MTR, VIEW_PSHISTORY, VIEW_RECHARGEHIST, VIEW_PHONEBOOK, 
	VIEW_PROMOTION, VIEW_VPN, VIEW_SUBINFO, VIEW_PERCHARGE, VIEW_RESERVATION, VIEW_OSAHISTORY, VIEW_DIAMETERHIST,

	CHANGE_BALANCE, CHANGE_PERCHARGE, CHANGE_CREDIT_LIMIT, CANCEL_RESERVATION, RECHARGE_SUBSCRIBER, USE_VOUCHER;

}
