package com.gnv.vnm.selfcare.core.adapter.rtbs.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-28T22:57:20.282+07:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://comverse-in.com/prepaid/ccws", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    /**
     * Retrieves all the identities of a Subscriber
     */
    @WebMethod(operationName = "GetSubscriberIdentities", action = "http://comverse-in.com/prepaid/ccws/GetSubscriberIdentities")
    @RequestWrapper(localName = "GetSubscriberIdentities", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetSubscriberIdentities")
    @ResponseWrapper(localName = "GetSubscriberIdentitiesResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetSubscriberIdentitiesResponse")
    @WebResult(name = "GetSubscriberIdentitiesResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfIdentity getSubscriberIdentities(
        @WebParam(name = "subscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberID
    );

    @WebMethod(operationName = "AssignBonusPlan", action = "http://comverse-in.com/prepaid/ccws/AssignBonusPlan")
    @RequestWrapper(localName = "AssignBonusPlan", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AssignBonusPlan")
    @ResponseWrapper(localName = "AssignBonusPlanResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AssignBonusPlanResponse")
    @WebResult(name = "AssignBonusPlanResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AssignBonusPlanResponse2 assignBonusPlan(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AssignBonusPlanRequest request
    );

    /**
     * Gets all the range map
     */
    @WebMethod(operationName = "GetRangeMap", action = "http://comverse-in.com/prepaid/ccws/GetRangeMap")
    @RequestWrapper(localName = "GetRangeMap", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetRangeMap")
    @ResponseWrapper(localName = "GetRangeMapResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetRangeMapResponse")
    @WebResult(name = "GetRangeMapResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfRange getRangeMap(
        @WebParam(name = "reloadData", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        boolean reloadData
    );

    /**
     * Gets all members for a group account.
     */
    @WebMethod(operationName = "GetAllGroupMembers", action = "http://comverse-in.com/prepaid/ccws/GetAllGroupMembers")
    @RequestWrapper(localName = "GetAllGroupMembers", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetAllGroupMembers")
    @ResponseWrapper(localName = "GetAllGroupMembersResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetAllGroupMembersResponse")
    @WebResult(name = "GetAllGroupMembersResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfSubscriberRetrieve getAllGroupMembers(
        @WebParam(name = "groupName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String groupName
    );

    @WebMethod(operationName = "DeleteCallingCircle", action = "http://comverse-in.com/prepaid/ccws/DeleteCallingCircle")
    @RequestWrapper(localName = "DeleteCallingCircle", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteCallingCircle")
    @ResponseWrapper(localName = "DeleteCallingCircleResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteCallingCircleResponse")
    @WebResult(name = "DeleteCallingCircleResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteCallingCircleResponse2 deleteCallingCircle(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteCallingCircleRequest request
    );

    /**
     * Retrieves the number of members in the group account.
     */
    @WebMethod(operationName = "GetGroupCount", action = "http://comverse-in.com/prepaid/ccws/GetGroupCount")
    @RequestWrapper(localName = "GetGroupCount", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetGroupCount")
    @ResponseWrapper(localName = "GetGroupCountResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetGroupCountResponse")
    @WebResult(name = "GetGroupCountResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public long getGroupCount(
        @WebParam(name = "groupName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String groupName
    );

    @WebMethod(operationName = "NonVoucherRecharge", action = "http://comverse-in.com/prepaid/ccws/NonVoucherRecharge")
    @RequestWrapper(localName = "NonVoucherRecharge", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.NonVoucherRecharge")
    @ResponseWrapper(localName = "NonVoucherRechargeResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.NonVoucherRechargeResponse")
    @WebResult(name = "NonVoucherRechargeResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean nonVoucherRecharge(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "rechValue", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        double rechValue,
        @WebParam(name = "rechDays", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        int rechDays,
        @WebParam(name = "rechComm", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String rechComm
    );

    @WebMethod(operationName = "RechargeAccountWithPI", action = "http://comverse-in.com/prepaid/ccws/RechargeAccountWithPI")
    @RequestWrapper(localName = "RechargeAccountWithPI", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RechargeAccountWithPI")
    @ResponseWrapper(localName = "RechargeAccountWithPIResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RechargeAccountWithPIResponse")
    @WebResult(name = "RechargeAccountWithPIResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RechargeAccountPIResponse rechargeAccountWithPI(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RechargeAccountPIRequest request
    );

    /**
     * Calls external recharge server to recharge based on INSwitch, Subscriber and Identity
     */
    @WebMethod(operationName = "ExternalNonVoucherRecharge", action = "http://comverse-in.com/prepaid/ccws/ExternalNonVoucherRecharge")
    @RequestWrapper(localName = "ExternalNonVoucherRecharge", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ExternalNonVoucherRecharge")
    @ResponseWrapper(localName = "ExternalNonVoucherRechargeResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ExternalNonVoucherRechargeResponse")
    @WebResult(name = "ExternalNonVoucherRechargeResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean externalNonVoucherRecharge(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "rechValue", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        double rechValue,
        @WebParam(name = "rechDays", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        int rechDays,
        @WebParam(name = "rechComm", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String rechComm,
        @WebParam(name = "INSwitchID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        int inSwitchID,
        @WebParam(name = "currencyConversionRate", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.math.BigDecimal currencyConversionRate
    );

    @WebMethod(operationName = "GetCacheEx", action = "http://comverse-in.com/prepaid/ccws/GetCacheEx")
    @RequestWrapper(localName = "GetCacheEx", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetCacheEx")
    @ResponseWrapper(localName = "GetCacheExResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetCacheExResponse")
    @WebResult(name = "GetCacheExResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ClientCache getCacheEx(
        @WebParam(name = "cacheRequest", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        long cacheRequest
    );

    /**
     * Modifies Preferred Number to the subscriber
     */
    @WebMethod(operationName = "ModifyPreferredNumberToSubscriber", action = "http://comverse-in.com/prepaid/ccws/ModifyPreferredNumberToSubscriber")
    @RequestWrapper(localName = "ModifyPreferredNumberToSubscriber", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifyPreferredNumberToSubscriber")
    @ResponseWrapper(localName = "ModifyPreferredNumberToSubscriberResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifyPreferredNumberToSubscriberResponse")
    @WebResult(name = "ModifyPreferredNumberToSubscriberResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PreferredNumberResponse modifyPreferredNumberToSubscriber(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PreferredNumberModifyRequest request
    );

    @WebMethod(operationName = "GetAccessNumbers", action = "http://comverse-in.com/prepaid/ccws/GetAccessNumbers")
    @RequestWrapper(localName = "GetAccessNumbers", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetAccessNumbers")
    @ResponseWrapper(localName = "GetAccessNumbersResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetAccessNumbersResponse")
    @WebResult(name = "GetAccessNumbersResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfAccessNumberInfo getAccessNumbers();

    /**
     * Changes the Old SubscriberID with New Subscriber ID
     */
    @WebMethod(operationName = "ChangeSubscriberID", action = "http://comverse-in.com/prepaid/ccws/ChangeSubscriberID")
    @RequestWrapper(localName = "ChangeSubscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeSubscriberID")
    @ResponseWrapper(localName = "ChangeSubscriberIDResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeSubscriberIDResponse")
    public void changeSubscriberID(
        @WebParam(name = "oldSubscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String oldSubscriberID,
        @WebParam(name = "newSubscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String newSubscriberID
    );

    /**
     * Gets all the service parameters
     */
    @WebMethod(operationName = "GetServiceParameters", action = "http://comverse-in.com/prepaid/ccws/GetServiceParameters")
    @RequestWrapper(localName = "GetServiceParameters", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetServiceParameters")
    @ResponseWrapper(localName = "GetServiceParametersResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetServiceParametersResponse")
    @WebResult(name = "GetServiceParametersResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfServiceParameter getServiceParameters(
        @WebParam(name = "reloadData", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        boolean reloadData
    );

    /**
     * Retrieves Subsriber information based on SubscriberID, informationToRetrieve and Identity
     */
    @WebMethod(operationName = "FastSubscriberRetrieve", action = "http://comverse-in.com/prepaid/ccws/RetrieveSubscriberFastWithIdentityWithHistoryForMultipleIdentities")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "RetrieveSubscriberFastWithIdentityWithHistoryForMultipleIdentitiesResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", partName = "parameters")
    public RetrieveSubscriberFastWithIdentityWithHistoryForMultipleIdentitiesResponse fastSubscriberRetrieve(
        @WebParam(partName = "parameters", name = "RetrieveSubscriberFastWithIdentityWithHistoryForMultipleIdentities", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        RetrieveSubscriberFastWithIdentityWithHistoryForMultipleIdentities parameters
    );

    /**
     * Recharges the Group Account based on the Group Name
     */
    @WebMethod(operationName = "RechargeAccountByGroupName", action = "http://comverse-in.com/prepaid/ccws/RechargeAccountByGroupName")
    @RequestWrapper(localName = "RechargeAccountByGroupName", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RechargeAccountByGroupName")
    @ResponseWrapper(localName = "RechargeAccountByGroupNameResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RechargeAccountByGroupNameResponse")
    @WebResult(name = "RechargeAccountByGroupNameResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfDeltaBalance rechargeAccountByGroupName(
        @WebParam(name = "groupName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String groupName,
        @WebParam(name = "secretCode", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String secretCode,
        @WebParam(name = "rechargeComment", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String rechargeComment
    );

    /**
     * Adds a member to a group account.
     */
    @WebMethod(operationName = "AddMemberToGroup", action = "http://comverse-in.com/prepaid/ccws/AddMemberToGroup")
    @RequestWrapper(localName = "AddMemberToGroup", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AddMemberToGroup")
    @ResponseWrapper(localName = "AddMemberToGroupResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AddMemberToGroupResponse")
    public void addMemberToGroup(
        @WebParam(name = "groupName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String groupName,
        @WebParam(name = "subscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberID,
        @WebParam(name = "identityName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identityName,
        @WebParam(name = "enableDefaults", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        boolean enableDefaults,
        @WebParam(name = "rechargeAllowed", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        boolean rechargeAllowed
    );

    /**
     * Gets all the global identities
     */
    @WebMethod(operationName = "GetGlobalIdentities", action = "http://comverse-in.com/prepaid/ccws/GetGlobalIdentities")
    @RequestWrapper(localName = "GetGlobalIdentities", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetGlobalIdentities")
    @ResponseWrapper(localName = "GetGlobalIdentitiesResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetGlobalIdentitiesResponse")
    @WebResult(name = "GetGlobalIdentitiesResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfIdentity getGlobalIdentities(
        @WebParam(name = "reloadData", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        boolean reloadData
    );

    @WebMethod(operationName = "NonVoucherRechargeGeneric", action = "http://comverse-in.com/prepaid/ccws/NonVoucherRechargeGeneric")
    @RequestWrapper(localName = "NonVoucherRechargeGeneric", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.NonVoucherRechargeGeneric")
    @ResponseWrapper(localName = "NonVoucherRechargeGenericResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.NonVoucherRechargeGenericResponse")
    @WebResult(name = "NonVoucherRechargeGenericResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.NonVoucherRechargeResponse2 nonVoucherRechargeGeneric(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.NonVoucherRechargeRequest request
    );

    @WebMethod(operationName = "CancelReservation", action = "http://comverse-in.com/prepaid/ccws/CancelReservation")
    @RequestWrapper(localName = "CancelReservation", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CancelReservation")
    @ResponseWrapper(localName = "CancelReservationResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CancelReservationResponse")
    @WebResult(name = "CancelReservationResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean cancelReservation(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "reservationId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        long reservationId,
        @WebParam(name = "sluName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String sluName,
        @WebParam(name = "processName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String processName,
        @WebParam(name = "crn", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String crn
    );

    @WebMethod(operationName = "CreateSubscriber", action = "http://comverse-in.com/prepaid/ccws/CreateSubscriber")
    @RequestWrapper(localName = "CreateSubscriber", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateSubscriber")
    @ResponseWrapper(localName = "CreateSubscriberResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateSubscriberResponse")
    @WebResult(name = "CreateSubscriberResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean createSubscriber(
        @WebParam(name = "subscriber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SubscriberCreate subscriber
    );

    @WebMethod(operationName = "DeleteNP", action = "http://comverse-in.com/prepaid/ccws/DeleteNP")
    @RequestWrapper(localName = "DeleteNP", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteNP")
    @ResponseWrapper(localName = "DeleteNPResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteNPResponse")
    public void deleteNP(
        @WebParam(name = "originalNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String originalNumber
    );

    /**
     * Forgives Debt of  Subscriber that went to Post Active State due to RC
     */
    @WebMethod(operationName = "ForgiveSubscriberDebt", action = "http://comverse-in.com/prepaid/ccws/ForgiveSubscriberDebt")
    @RequestWrapper(localName = "ForgiveSubscriberDebt", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ForgiveSubscriberDebt")
    @ResponseWrapper(localName = "ForgiveSubscriberDebtResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ForgiveSubscriberDebtResponse")
    @WebResult(name = "ForgiveSubscriberDebtResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ForgiveSubscriberDebtResponse2 forgiveSubscriberDebt(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ForgiveSubscriberDebtRequest request
    );

    @WebMethod(operationName = "ChangePassword", action = "http://comverse-in.com/prepaid/ccws/ChangePassword")
    @RequestWrapper(localName = "ChangePassword", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangePassword")
    @ResponseWrapper(localName = "ChangePasswordResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangePasswordResponse")
    @WebResult(name = "ChangePasswordResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean changePassword(
        @WebParam(name = "newPassword", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String newPassword
    );

    @WebMethod(operationName = "SendSMSNotification", action = "http://comverse-in.com/prepaid/ccws/SendSMSNotification")
    @RequestWrapper(localName = "SendSMSNotification", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SendSMSNotification")
    @ResponseWrapper(localName = "SendSMSNotificationResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SendSMSNotificationResponse")
    @WebResult(name = "SendSMSNotificationResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean sendSMSNotification(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "notificationMSG", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String notificationMSG,
        @WebParam(name = "notificationInterFaceName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String notificationInterFaceName,
        @WebParam(name = "useUnicode", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        int useUnicode
    );

    @WebMethod(operationName = "ChangeCallingCircle", action = "http://comverse-in.com/prepaid/ccws/ChangeCallingCircle")
    @RequestWrapper(localName = "ChangeCallingCircle", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeCallingCircle")
    @ResponseWrapper(localName = "ChangeCallingCircleResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeCallingCircleResponse")
    @WebResult(name = "ChangeCallingCircleResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeCallingCircleResponse2 changeCallingCircle(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeCallingCircleRequest request
    );

    @WebMethod(operationName = "SetAccumulatorValue", action = "http://comverse-in.com/prepaid/ccws/SetAccumulatorValue")
    @RequestWrapper(localName = "SetAccumulatorValue", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SetAccumulatorValue")
    @ResponseWrapper(localName = "SetAccumulatorValueResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SetAccumulatorValueResponse")
    @WebResult(name = "SetAccumulatorValueResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SetAccumulatorValueResponse2 setAccumulatorValue(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SetAccumulatorValueRequest request
    );

    @WebMethod(operationName = "GetSpecialHomeAreas", action = "http://comverse-in.com/prepaid/ccws/GetSpecialHomeAreas")
    @RequestWrapper(localName = "GetSpecialHomeAreas", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetSpecialHomeAreas")
    @ResponseWrapper(localName = "GetSpecialHomeAreasResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetSpecialHomeAreasResponse")
    @WebResult(name = "GetSpecialHomeAreasResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfString getSpecialHomeAreas();

    /**
     * Reserves the Voucher for the requested INSwitch, Subscriber and Identity
     */
    @WebMethod(operationName = "ReserveVoucher", action = "http://comverse-in.com/prepaid/ccws/ReserveVoucher")
    @RequestWrapper(localName = "ReserveVoucher", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ReserveVoucher")
    @ResponseWrapper(localName = "ReserveVoucherResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ReserveVoucherResponse")
    @WebResult(name = "ReserveVoucherResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.VoucherEntity reserveVoucher(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "INSwitchID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        int inSwitchID,
        @WebParam(name = "secreteCode", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String secreteCode
    );

    @WebMethod(operationName = "CreatePhonebookNumber", action = "http://comverse-in.com/prepaid/ccws/CreatePhonebookNumber")
    @RequestWrapper(localName = "CreatePhonebookNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreatePhonebookNumber")
    @ResponseWrapper(localName = "CreatePhonebookNumberResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreatePhonebookNumberResponse")
    @WebResult(name = "CreatePhonebookNumberResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PhonebookNumberResponse createPhonebookNumber(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreatePhonebookNumberRequest request
    );

    /**
     * Synchronization of data between LEAP and PPS
     */
    @WebMethod(operationName = "CatalogSync", action = "http://comverse-in.com/prepaid/ccws/CatalogSync")
    @RequestWrapper(localName = "CatalogSync", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CatalogSync")
    @ResponseWrapper(localName = "CatalogSyncResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CatalogSyncResponse")
    public void catalogSync(
        @WebParam(name = "versionID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        int versionID
    );

    @WebMethod(operationName = "DeletePeriodicCharge", action = "http://comverse-in.com/prepaid/ccws/DeletePeriodicCharge")
    @RequestWrapper(localName = "DeletePeriodicCharge", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeletePeriodicCharge")
    @ResponseWrapper(localName = "DeletePeriodicChargeResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeletePeriodicChargeResponse")
    @WebResult(name = "DeletePeriodicChargeResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PeriodicChargeResponse deletePeriodicCharge(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeletePeriodicChargeRequest request
    );

    @WebMethod(operationName = "CreateVoucher", action = "http://comverse-in.com/prepaid/ccws/CreateVoucher")
    @RequestWrapper(localName = "CreateVoucher", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateVoucher")
    @ResponseWrapper(localName = "CreateVoucherResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateVoucherResponse")
    @WebResult(name = "CreateVoucherResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean createVoucher(
        @WebParam(name = "voucher", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.VoucherEntity voucher
    );

    /**
     * Modifies the requested currency conversion information to the system
     */
    @WebMethod(operationName = "ModifyCurrencyConversion", action = "http://comverse-in.com/prepaid/ccws/ModifyCurrencyConversion")
    @RequestWrapper(localName = "ModifyCurrencyConversion", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifyCurrencyConversion")
    @ResponseWrapper(localName = "ModifyCurrencyConversionResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifyCurrencyConversionResponse")
    @WebResult(name = "ModifyCurrencyConversionResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean modifyCurrencyConversion(
        @WebParam(name = "currencyConversion", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CurrencyConversionModify currencyConversion
    );

    @WebMethod(operationName = "GetVersionId", action = "http://comverse-in.com/prepaid/ccws/GetVersionId")
    @RequestWrapper(localName = "GetVersionId", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetVersionId")
    @ResponseWrapper(localName = "GetVersionIdResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetVersionIdResponse")
    @WebResult(name = "GetVersionIdResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public int getVersionId();

    @WebMethod(operationName = "UpdateSubscriberDataForAllIdentities", action = "http://comverse-in.com/prepaid/ccws/UpdateSubscriberDataForAllIdentities")
    @RequestWrapper(localName = "UpdateSubscriberDataForAllIdentities", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UpdateSubscriberDataForAllIdentities")
    @ResponseWrapper(localName = "UpdateSubscriberDataForAllIdentitiesResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UpdateSubscriberDataForAllIdentitiesResponse")
    @WebResult(name = "UpdateSubscriberDataForAllIdentitiesResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UpdateSubscriberDataForAllIdentityResponse updateSubscriberDataForAllIdentities(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UpdateSubscriberDataForAllIdentityRequest request
    );

    /**
     * Applies promised payment to subscriber
     */
    @WebMethod(operationName = "PromisedPayment", action = "http://comverse-in.com/prepaid/ccws/PromisedPayment")
    @RequestWrapper(localName = "PromisedPayment", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PromisedPayment")
    @ResponseWrapper(localName = "PromisedPaymentResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PromisedPaymentResponse")
    @WebResult(name = "PromisedPaymentResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PromisedPaymentResponse2 promisedPayment(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PromisedPaymentRequest request
    );

    /**
     * Adds the requested currency conversion information to the system
     */
    @WebMethod(operationName = "AddCurrencyConversion", action = "http://comverse-in.com/prepaid/ccws/AddCurrencyConversion")
    @RequestWrapper(localName = "AddCurrencyConversion", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AddCurrencyConversion")
    @ResponseWrapper(localName = "AddCurrencyConversionResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AddCurrencyConversionResponse")
    @WebResult(name = "AddCurrencyConversionResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean addCurrencyConversion(
        @WebParam(name = "currencyConversion", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CurrencyConversionCreate currencyConversion
    );

    @WebMethod(operationName = "CreditAccumulator", action = "http://comverse-in.com/prepaid/ccws/CreditAccumulator")
    @RequestWrapper(localName = "CreditAccumulator", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreditAccumulator")
    @ResponseWrapper(localName = "CreditAccumulatorResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreditAccumulatorResponse")
    public void creditAccumulator(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "credits", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfCreditAccumulator credits
    );

    @WebMethod(operationName = "CreateSpecialHomeArea", action = "http://comverse-in.com/prepaid/ccws/CreateSpecialHomeArea")
    @RequestWrapper(localName = "CreateSpecialHomeArea", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateSpecialHomeArea")
    @ResponseWrapper(localName = "CreateSpecialHomeAreaResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateSpecialHomeAreaResponse")
    @WebResult(name = "CreateSpecialHomeAreaResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean createSpecialHomeArea(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SpecialHomeAreaRequest request
    );

    @WebMethod(operationName = "RetrieveVoucherBySecretCode", action = "http://comverse-in.com/prepaid/ccws/RetrieveVoucherBySecretCode")
    @RequestWrapper(localName = "RetrieveVoucherBySecretCode", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveVoucherBySecretCode")
    @ResponseWrapper(localName = "RetrieveVoucherBySecretCodeResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveVoucherBySecretCodeResponse")
    @WebResult(name = "RetrieveVoucherBySecretCodeResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.VoucherEntity retrieveVoucherBySecretCode(
        @WebParam(name = "secretCode", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String secretCode
    );

    /**
     * Modifies group account.
     */
    @WebMethod(operationName = "ModifyGroupAccount", action = "http://comverse-in.com/prepaid/ccws/ModifyGroupAccount")
    @RequestWrapper(localName = "ModifyGroupAccount", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifyGroupAccount")
    @ResponseWrapper(localName = "ModifyGroupAccountResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifyGroupAccountResponse")
    public void modifyGroupAccount(
        @WebParam(name = "groupAccountModify", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GroupAccountModify groupAccountModify
    );

    /**
     * Recharges the subscriber based only on subscriber ID
     */
    @WebMethod(operationName = "RechargeAccount4250", action = "http://comverse-in.com/prepaid/ccws/RechargeAccount")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "RechargeAccountResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", partName = "parameters")
    public RechargeAccountResponse rechargeAccount4250(
        @WebParam(partName = "parameters", name = "RechargeAccount", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        RechargeAccount parameters
    );

    /**
     * Retrieves the group Owner from  group name
     */
    @WebMethod(operationName = "GetGroupOwner", action = "http://comverse-in.com/prepaid/ccws/GetGroupOwner")
    @RequestWrapper(localName = "GetGroupOwner", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetGroupOwner")
    @ResponseWrapper(localName = "GetGroupOwnerResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetGroupOwnerResponse")
    @WebResult(name = "GetGroupOwnerResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SubscriberBasic getGroupOwner(
        @WebParam(name = "groupName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String groupName
    );

    /**
     * Retrieves Subsriber Limited information based on SubscriberID and Identity
     */
    @WebMethod(operationName = "RetrieveSubscriberLite", action = "http://comverse-in.com/prepaid/ccws/RetrieveSubscriberLite")
    @RequestWrapper(localName = "RetrieveSubscriberLite", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveSubscriberLite")
    @ResponseWrapper(localName = "RetrieveSubscriberLiteResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveSubscriberLiteResponse")
    @WebResult(name = "RetrieveSubscriberLiteResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SubscriberRetrieveLite retrieveSubscriberLite(
        @WebParam(name = "subscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberID,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity
    );

    /**
     * Removes Preferred Number from the subscriber
     */
    @WebMethod(operationName = "RemovePreferredNumberFromSubscriber", action = "http://comverse-in.com/prepaid/ccws/RemovePreferredNumberFromSubscriber")
    @RequestWrapper(localName = "RemovePreferredNumberFromSubscriber", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RemovePreferredNumberFromSubscriber")
    @ResponseWrapper(localName = "RemovePreferredNumberFromSubscriberResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RemovePreferredNumberFromSubscriberResponse")
    @WebResult(name = "RemovePreferredNumberFromSubscriberResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PreferredNumberResponse removePreferredNumberFromSubscriber(
        @WebParam(name = "subscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberID,
        @WebParam(name = "subscriberIdentity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberIdentity
    );

    @WebMethod(operationName = "GetSubscriberDataForAllIdentities", action = "http://comverse-in.com/prepaid/ccws/GetSubscriberDataForAllIdentities")
    @RequestWrapper(localName = "GetSubscriberDataForAllIdentities", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetSubscriberDataForAllIdentities")
    @ResponseWrapper(localName = "GetSubscriberDataForAllIdentitiesResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetSubscriberDataForAllIdentitiesResponse")
    @WebResult(name = "GetSubscriberDataForAllIdentitiesResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetSubscriberDataForAllIdentityResponse getSubscriberDataForAllIdentities(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetSubscriberDataForAllIdentityRequest request
    );

    @WebMethod(operationName = "GetLocations", action = "http://comverse-in.com/prepaid/ccws/GetLocations")
    @RequestWrapper(localName = "GetLocations", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetLocations")
    @ResponseWrapper(localName = "GetLocationsResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetLocationsResponse")
    @WebResult(name = "GetLocationsResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfString getLocations();

    @WebMethod(operationName = "IVRGetGroupAccountWithOwner", action = "http://comverse-in.com/prepaid/ccws/IVRGetGroupAccountWithOwner")
    @RequestWrapper(localName = "IVRGetGroupAccountWithOwner", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRGetGroupAccountWithOwner")
    @ResponseWrapper(localName = "IVRGetGroupAccountWithOwnerResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRGetGroupAccountWithOwnerResponse")
    @WebResult(name = "IVRGetGroupAccountWithOwnerResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRGetGroupAccountWithOwnerResponse2 ivrGetGroupAccountWithOwner(
        @WebParam(name = "IVRGetGroupAccountWithOwnerRequest", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRGetGroupAccountWithOwnerRequest ivrGetGroupAccountWithOwnerRequest
    );

    /**
     * Credit limit reset process
     */
    @WebMethod(operationName = "PostpaidCreditLimitReset", action = "http://comverse-in.com/prepaid/ccws/PostpaidCreditLimitReset")
    @RequestWrapper(localName = "PostpaidCreditLimitReset", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PostpaidCreditLimitReset")
    @ResponseWrapper(localName = "PostpaidCreditLimitResetResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PostpaidCreditLimitResetResponse")
    public void postpaidCreditLimitReset(
        @WebParam(name = "billCycle", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        int billCycle,
        @WebParam(name = "billPeriod", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        javax.xml.datatype.XMLGregorianCalendar billPeriod,
        @WebParam(name = "tableName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String tableName
    );

    @WebMethod(operationName = "RetrieveNP", action = "http://comverse-in.com/prepaid/ccws/RetrieveNP")
    @RequestWrapper(localName = "RetrieveNP", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveNP")
    @ResponseWrapper(localName = "RetrieveNPResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveNPResponse")
    @WebResult(name = "RetrieveNPResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.NPEntity retrieveNP(
        @WebParam(name = "originalNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String originalNumber
    );

    /**
     * Removes requested offer from subscriber
     */
    @WebMethod(operationName = "UnsubscribeOffer", action = "http://comverse-in.com/prepaid/ccws/UnsubscribeOffer")
    @RequestWrapper(localName = "UnsubscribeOffer", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UnsubscribeOffer")
    @ResponseWrapper(localName = "UnsubscribeOfferResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UnsubscribeOfferResponse")
    @WebResult(name = "UnsubscribeOfferResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean unsubscribeOffer(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.OfferUnsubscribeRequest request
    );

    @WebMethod(operationName = "IVRRechargeBySubscriberWithSessionValue", action = "http://comverse-in.com/prepaid/ccws/IVRRechargeBySubscriberWithSessionValue")
    @RequestWrapper(localName = "IVRRechargeBySubscriberWithSessionValue", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRRechargeBySubscriberWithSessionValue")
    @ResponseWrapper(localName = "IVRRechargeBySubscriberWithSessionValueResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRRechargeBySubscriberWithSessionValueResponse")
    @WebResult(name = "IVRRechargeBySubscriberWithSessionValueResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRDeltaBalanceWithSessionValueResponse ivrRechargeBySubscriberWithSessionValue(
        @WebParam(name = "IVRDeltaBalanceWithSessionValueRequest", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRDeltaBalanceWithSessionValueRequest ivrDeltaBalanceWithSessionValueRequest
    );

    @WebMethod(operationName = "UseVoucher", action = "http://comverse-in.com/prepaid/ccws/UseVoucher")
    @RequestWrapper(localName = "UseVoucher", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UseVoucher")
    @ResponseWrapper(localName = "UseVoucherResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UseVoucherResponse")
    @WebResult(name = "UseVoucherResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public int useVoucher(
        @WebParam(name = "secretCode", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String secretCode,
        @WebParam(name = "useDate", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        javax.xml.datatype.XMLGregorianCalendar useDate,
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity
    );

    /**
     * Retrieves Subsriber information based on SubscriberID, informationToRetrieve and Identity
     */
    @WebMethod(operationName = "RetrieveSubscriberWithIdentityNoHistory", action = "http://comverse-in.com/prepaid/ccws/RetrieveSubscriberWithIdentityNoHistory")
    @RequestWrapper(localName = "RetrieveSubscriberWithIdentityNoHistory", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveSubscriberWithIdentityNoHistory")
    @ResponseWrapper(localName = "RetrieveSubscriberWithIdentityNoHistoryResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveSubscriberWithIdentityNoHistoryResponse")
    @WebResult(name = "RetrieveSubscriberWithIdentityNoHistoryResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SubscriberRetrieve retrieveSubscriberWithIdentityNoHistory(
        @WebParam(name = "subscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberID,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "informationToRetrieve", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        int informationToRetrieve
    );

    @WebMethod(operationName = "GetNonVersionCache", action = "http://comverse-in.com/prepaid/ccws/GetNonVersionCache")
    @RequestWrapper(localName = "GetNonVersionCache", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetNonVersionCache")
    @ResponseWrapper(localName = "GetNonVersionCacheResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetNonVersionCacheResponse")
    @WebResult(name = "GetNonVersionCacheResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.NonVersionCache getNonVersionCache(
        @WebParam(name = "reloadData", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        boolean reloadData
    );

    @WebMethod(operationName = "GetUserConfig", action = "http://comverse-in.com/prepaid/ccws/GetUserConfig")
    @RequestWrapper(localName = "GetUserConfig", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetUserConfig")
    @ResponseWrapper(localName = "GetUserConfigResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetUserConfigResponse")
    @WebResult(name = "GetUserConfigResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public java.lang.String getUserConfig();

    @WebMethod(operationName = "RetrieveCircleMembers", action = "http://comverse-in.com/prepaid/ccws/RetrieveCircleMembers")
    @RequestWrapper(localName = "RetrieveCircleMembers", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveCircleMembers")
    @ResponseWrapper(localName = "RetrieveCircleMembersResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveCircleMembersResponse")
    @WebResult(name = "RetrieveCircleMembersResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveCirclesMembersResponse retrieveCircleMembers(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveCircleMembersRequest request
    );

    /**
     * Changes the subscriber state for all the identities
     */
    @WebMethod(operationName = "ChangeSubStatusAllIdentities", action = "http://comverse-in.com/prepaid/ccws/ChangeSubStatusAllIdentities")
    @RequestWrapper(localName = "ChangeSubStatusAllIdentities", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeSubStatusAllIdentities")
    @ResponseWrapper(localName = "ChangeSubStatusAllIdentitiesResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeSubStatusAllIdentitiesResponse")
    public void changeSubStatusAllIdentities(
        @WebParam(name = "subscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberID,
        @WebParam(name = "identityStatus", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfIdentityStatus identityStatus
    );

    @WebMethod(operationName = "DeletePhonebookNumber", action = "http://comverse-in.com/prepaid/ccws/DeletePhonebookNumber")
    @RequestWrapper(localName = "DeletePhonebookNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeletePhonebookNumber")
    @ResponseWrapper(localName = "DeletePhonebookNumberResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeletePhonebookNumberResponse")
    @WebResult(name = "DeletePhonebookNumberResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PhonebookNumberResponse deletePhonebookNumber(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeletePhonebookNumberRequest request
    );

    /**
     * Consumes the Voucher for the requested INSwitch, Subscriber and Identity
     */
    @WebMethod(operationName = "ConsumeVoucher", action = "http://comverse-in.com/prepaid/ccws/ConsumeVoucher")
    @RequestWrapper(localName = "ConsumeVoucher", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ConsumeVoucher")
    @ResponseWrapper(localName = "ConsumeVoucherResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ConsumeVoucherResponse")
    @WebResult(name = "ConsumeVoucherResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.VoucherEntity consumeVoucher(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "INSwitchID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        int inSwitchID,
        @WebParam(name = "secreteCode", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String secreteCode
    );

    @WebMethod(operationName = "GetCache", action = "http://comverse-in.com/prepaid/ccws/GetCache")
    @RequestWrapper(localName = "GetCache", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetCache")
    @ResponseWrapper(localName = "GetCacheResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetCacheResponse")
    @WebResult(name = "GetCacheResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ClientCache getCache();

    @WebMethod(operationName = "RemoveBonusPlan", action = "http://comverse-in.com/prepaid/ccws/RemoveBonusPlan")
    @RequestWrapper(localName = "RemoveBonusPlan", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RemoveBonusPlan")
    @ResponseWrapper(localName = "RemoveBonusPlanResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RemoveBonusPlanResponse")
    @WebResult(name = "RemoveBonusPlanResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RemoveBonusPlanResponse2 removeBonusPlan(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RemoveBonusPlanRequest request
    );

    /**
     * Adds Preferred Number to the subscriber
     */
    @WebMethod(operationName = "AddPreferredNumberToSubscriber", action = "http://comverse-in.com/prepaid/ccws/AddPreferredNumberToSubscriber")
    @RequestWrapper(localName = "AddPreferredNumberToSubscriber", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AddPreferredNumberToSubscriber")
    @ResponseWrapper(localName = "AddPreferredNumberToSubscriberResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AddPreferredNumberToSubscriberResponse")
    @WebResult(name = "AddPreferredNumberToSubscriberResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PreferredNumberResponse addPreferredNumberToSubscriber(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PreferredNumberAddRequest request
    );

    /**
     * Recharges the subscriber account based on the subscriber ID
     */
    @WebMethod(operationName = "RechargeAccountBySubscriber", action = "http://comverse-in.com/prepaid/ccws/RechargeAccountBySubscriber")
    @RequestWrapper(localName = "RechargeAccountBySubscriber", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RechargeAccountBySubscriber")
    @ResponseWrapper(localName = "RechargeAccountBySubscriberResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RechargeAccountBySubscriberResponse")
    @WebResult(name = "RechargeAccountBySubscriberResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfDeltaBalance rechargeAccountBySubscriber(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "secretCode", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String secretCode,
        @WebParam(name = "rechargeComment", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String rechargeComment
    );

    @WebMethod(operationName = "DeleteVoucher", action = "http://comverse-in.com/prepaid/ccws/DeleteVoucher")
    @RequestWrapper(localName = "DeleteVoucher", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteVoucher")
    @ResponseWrapper(localName = "DeleteVoucherResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteVoucherResponse")
    @WebResult(name = "DeleteVoucherResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public int deleteVoucher(
        @WebParam(name = "batchNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.math.BigDecimal batchNumber,
        @WebParam(name = "startSerial", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.math.BigDecimal startSerial,
        @WebParam(name = "endSerial", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.math.BigDecimal endSerial
    );

    @WebMethod(operationName = "DeleteSubscriber", action = "http://comverse-in.com/prepaid/ccws/DeleteSubscriber")
    @RequestWrapper(localName = "DeleteSubscriber", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteSubscriber")
    @ResponseWrapper(localName = "DeleteSubscriberResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteSubscriberResponse")
    @WebResult(name = "DeleteSubscriberResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean deleteSubscriber(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity
    );

    @WebMethod(operationName = "UpdateNP", action = "http://comverse-in.com/prepaid/ccws/UpdateNP")
    @RequestWrapper(localName = "UpdateNP", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UpdateNP")
    @ResponseWrapper(localName = "UpdateNPResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UpdateNPResponse")
    public void updateNP(
        @WebParam(name = "originalNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String originalNumber,
        @WebParam(name = "routedNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String routedNumber
    );

    /**
     * Deletes group account.
     */
    @WebMethod(operationName = "DeleteGroupAccount", action = "http://comverse-in.com/prepaid/ccws/DeleteGroupAccount")
    @RequestWrapper(localName = "DeleteGroupAccount", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteGroupAccount")
    @ResponseWrapper(localName = "DeleteGroupAccountResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteGroupAccountResponse")
    public void deleteGroupAccount(
        @WebParam(name = "groupName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String groupName
    );

    @WebMethod(operationName = "DeleteSpecialHomeArea", action = "http://comverse-in.com/prepaid/ccws/DeleteSpecialHomeArea")
    @RequestWrapper(localName = "DeleteSpecialHomeArea", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteSpecialHomeArea")
    @ResponseWrapper(localName = "DeleteSpecialHomeAreaResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteSpecialHomeAreaResponse")
    @WebResult(name = "DeleteSpecialHomeAreaResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean deleteSpecialHomeArea(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteSpecialHomeAreaRequest request
    );

    /**
     * Deletes the requested currency conversion information from the system
     */
    @WebMethod(operationName = "DeleteCurrencyConversion", action = "http://comverse-in.com/prepaid/ccws/DeleteCurrencyConversion")
    @RequestWrapper(localName = "DeleteCurrencyConversion", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteCurrencyConversion")
    @ResponseWrapper(localName = "DeleteCurrencyConversionResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteCurrencyConversionResponse")
    @WebResult(name = "DeleteCurrencyConversionResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean deleteCurrencyConversion(
        @WebParam(name = "currencyConversion", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CurrencyConversionDelete currencyConversion
    );

    /**
     * Gets all the charge codes
     */
    @WebMethod(operationName = "GetChargeCodes", action = "http://comverse-in.com/prepaid/ccws/GetChargeCodes")
    @RequestWrapper(localName = "GetChargeCodes", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetChargeCodes")
    @ResponseWrapper(localName = "GetChargeCodesResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetChargeCodesResponse")
    @WebResult(name = "GetChargeCodesResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfString getChargeCodes(
        @WebParam(name = "reloadData", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        boolean reloadData
    );

    @WebMethod(operationName = "GetRoles", action = "http://comverse-in.com/prepaid/ccws/GetRoles")
    @RequestWrapper(localName = "GetRoles", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetRoles")
    @ResponseWrapper(localName = "GetRolesResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetRolesResponse")
    @WebResult(name = "GetRolesResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfString getRoles();

    @WebMethod(operationName = "RechargeBilledAccount", action = "http://comverse-in.com/prepaid/ccws/RechargeBilledAccount")
    @RequestWrapper(localName = "RechargeBilledAccount", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RechargeBilledAccount")
    @ResponseWrapper(localName = "RechargeBilledAccountResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RechargeBilledAccountResponse")
    @WebResult(name = "RechargeBilledAccountResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PostpaidDeltaBalance rechargeBilledAccount(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "secretCode", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String secretCode,
        @WebParam(name = "rechargeComment", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String rechargeComment
    );

    @WebMethod(operationName = "GetPasswordWarningDays", action = "http://comverse-in.com/prepaid/ccws/GetPasswordWarningDays")
    @RequestWrapper(localName = "GetPasswordWarningDays", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetPasswordWarningDays")
    @ResponseWrapper(localName = "GetPasswordWarningDaysResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetPasswordWarningDaysResponse")
    @WebResult(name = "GetPasswordWarningDaysResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public int getPasswordWarningDays();

    @WebMethod(operationName = "AuditEvent", action = "http://comverse-in.com/prepaid/ccws/AuditEvent")
    @RequestWrapper(localName = "AuditEvent", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AuditEvent")
    @ResponseWrapper(localName = "AuditEventResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AuditEventResponse")
    public void auditEvent(
        @WebParam(name = "auditEvent", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.AuditEvent2 auditEvent
    );

    @WebMethod(operationName = "CreditAccount", action = "http://comverse-in.com/prepaid/ccws/CreditAccount")
    @RequestWrapper(localName = "CreditAccount", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreditAccount")
    @ResponseWrapper(localName = "CreditAccountResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreditAccountResponse")
    @WebResult(name = "CreditAccountResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean creditAccount(
        @WebParam(name = "subscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberID,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "subCreditBalances", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfBalanceCreditAccount subCreditBalances,
        @WebParam(name = "balanceChangeCode", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String balanceChangeCode,
        @WebParam(name = "balanceChangeComment", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String balanceChangeComment
    );

    /**
     * Retrieves the requested currency conversion information from the system
     */
    @WebMethod(operationName = "RetrieveCurrencyConversion", action = "http://comverse-in.com/prepaid/ccws/RetrieveCurrencyConversion")
    @RequestWrapper(localName = "RetrieveCurrencyConversion", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveCurrencyConversion")
    @ResponseWrapper(localName = "RetrieveCurrencyConversionResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveCurrencyConversionResponse")
    @WebResult(name = "RetrieveCurrencyConversionResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfCurrencyConversionRetrieve retrieveCurrencyConversion(
        @WebParam(name = "currencyConversion", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CurrencyConversionDelete currencyConversion
    );

    /**
     * Retrieves Subsriber information based on SubscriberID, informationToRetrieve and Identity
     */
    @WebMethod(operationName = "RetrieveSubscriberWithIdentityWithHistoryForMultipleIdentities", action = "http://comverse-in.com/prepaid/ccws/RetrieveSubscriberWithIdentityWithHistoryForMultipleIdentities")
    @RequestWrapper(localName = "RetrieveSubscriberWithIdentityWithHistoryForMultipleIdentities", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveSubscriberWithIdentityWithHistoryForMultipleIdentities")
    @ResponseWrapper(localName = "RetrieveSubscriberWithIdentityWithHistoryForMultipleIdentitiesResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveSubscriberWithIdentityWithHistoryForMultipleIdentitiesResponse")
    @WebResult(name = "RetrieveSubscriberWithIdentityWithHistoryForMultipleIdentitiesResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SubscriberRetrieve retrieveSubscriberWithIdentityWithHistoryForMultipleIdentities(
        @WebParam(name = "subscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberID,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity,
        @WebParam(name = "informationToRetrieve", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        int informationToRetrieve,
        @WebParam(name = "startDate", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        javax.xml.datatype.XMLGregorianCalendar endDate,
        @WebParam(name = "IsAllIdentity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        boolean isAllIdentity
    );

    @WebMethod(operationName = "CreateHomeLocation", action = "http://comverse-in.com/prepaid/ccws/CreateHomeLocation")
    @RequestWrapper(localName = "CreateHomeLocation", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateHomeLocation")
    @ResponseWrapper(localName = "CreateHomeLocationResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateHomeLocationResponse")
    @WebResult(name = "CreateHomeLocationResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.HomeLocationResponse createHomeLocation(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateHomeLocationRequest request
    );

    @WebMethod(operationName = "ModifySpecialHomeArea", action = "http://comverse-in.com/prepaid/ccws/ModifySpecialHomeArea")
    @RequestWrapper(localName = "ModifySpecialHomeArea", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifySpecialHomeArea")
    @ResponseWrapper(localName = "ModifySpecialHomeAreaResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifySpecialHomeAreaResponse")
    @WebResult(name = "ModifySpecialHomeAreaResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean modifySpecialHomeArea(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SpecialHomeAreaRequest request
    );

    @WebMethod(operationName = "ChangeCOS", action = "http://comverse-in.com/prepaid/ccws/ChangeCOS")
    @RequestWrapper(localName = "ChangeCOS", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeCOS")
    @ResponseWrapper(localName = "ChangeCOSResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeCOSResponse")
    @WebResult(name = "ChangeCOSResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeCOSResponse2 changeCOS(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ChangeCOSRequest request
    );

    @WebMethod(operationName = "SetSubscriberHappyHour", action = "http://comverse-in.com/prepaid/ccws/SetSubscriberHappyHour")
    @RequestWrapper(localName = "SetSubscriberHappyHour", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SetSubscriberHappyHour")
    @ResponseWrapper(localName = "SetSubscriberHappyHourResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SetSubscriberHappyHourResponse")
    @WebResult(name = "SetSubscriberHappyHourResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean setSubscriberHappyHour(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.HappyHourRequest request
    );

    @WebMethod(operationName = "RetrieveVoucherByBatchSerial", action = "http://comverse-in.com/prepaid/ccws/RetrieveVoucherByBatchSerial")
    @RequestWrapper(localName = "RetrieveVoucherByBatchSerial", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveVoucherByBatchSerial")
    @ResponseWrapper(localName = "RetrieveVoucherByBatchSerialResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveVoucherByBatchSerialResponse")
    @WebResult(name = "RetrieveVoucherByBatchSerialResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.VoucherEntity retrieveVoucherByBatchSerial(
        @WebParam(name = "batchNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        long batchNumber,
        @WebParam(name = "serialNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        long serialNumber
    );

    @WebMethod(operationName = "CreatePeriodicCharge", action = "http://comverse-in.com/prepaid/ccws/CreatePeriodicCharge")
    @RequestWrapper(localName = "CreatePeriodicCharge", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreatePeriodicCharge")
    @ResponseWrapper(localName = "CreatePeriodicChargeResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreatePeriodicChargeResponse")
    @WebResult(name = "CreatePeriodicChargeResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.PeriodicChargeResponse createPeriodicCharge(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreatePeriodicChargeRequest request
    );

    /**
     * Gets a group account.
     */
    @WebMethod(operationName = "GetGroupAccount", action = "http://comverse-in.com/prepaid/ccws/GetGroupAccount")
    @RequestWrapper(localName = "GetGroupAccount", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetGroupAccount")
    @ResponseWrapper(localName = "GetGroupAccountResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GetGroupAccountResponse")
    @WebResult(name = "GetGroupAccountResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GroupAccountRetrieve getGroupAccount(
        @WebParam(name = "groupName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String groupName
    );

    @WebMethod(operationName = "DeleteHomeLocation", action = "http://comverse-in.com/prepaid/ccws/DeleteHomeLocation")
    @RequestWrapper(localName = "DeleteHomeLocation", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteHomeLocation")
    @ResponseWrapper(localName = "DeleteHomeLocationResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteHomeLocationResponse")
    @WebResult(name = "DeleteHomeLocationResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.HomeLocationResponse deleteHomeLocation(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.DeleteHomeLocationRequest request
    );

    @WebMethod(operationName = "IVRChangeLanguage", action = "http://comverse-in.com/prepaid/ccws/IVRChangeLanguage")
    @RequestWrapper(localName = "IVRChangeLanguage", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRChangeLanguage")
    @ResponseWrapper(localName = "IVRChangeLanguageResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRChangeLanguageResponse")
    @WebResult(name = "IVRChangeLanguageResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRChangeLanguageResponse2 ivrChangeLanguage(
        @WebParam(name = "IVRChangeLanguageRequest", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.IVRChangeLanguageRequest ivrChangeLanguageRequest
    );

    @WebMethod(operationName = "ModifySubscriber", action = "http://comverse-in.com/prepaid/ccws/ModifySubscriber")
    @RequestWrapper(localName = "ModifySubscriber", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifySubscriber")
    @ResponseWrapper(localName = "ModifySubscriberResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifySubscriberResponse")
    @WebResult(name = "ModifySubscriberResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean modifySubscriber(
        @WebParam(name = "subscriber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SubscriberModify subscriber
    );

    @WebMethod(operationName = "ModifyVoucher", action = "http://comverse-in.com/prepaid/ccws/ModifyVoucher")
    @RequestWrapper(localName = "ModifyVoucher", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifyVoucher")
    @ResponseWrapper(localName = "ModifyVoucherResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifyVoucherResponse")
    @WebResult(name = "ModifyVoucherResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public int modifyVoucher(
        @WebParam(name = "batchNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.math.BigDecimal batchNumber,
        @WebParam(name = "newStateName", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String newStateName,
        @WebParam(name = "orderNumber", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String orderNumber,
        @WebParam(name = "distributor", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String distributor,
        @WebParam(name = "shipDate", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        javax.xml.datatype.XMLGregorianCalendar shipDate,
        @WebParam(name = "expirationDate", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        javax.xml.datatype.XMLGregorianCalendar expirationDate,
        @WebParam(name = "startSerial", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.math.BigDecimal startSerial,
        @WebParam(name = "endSerial", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.math.BigDecimal endSerial
    );

    @WebMethod(operationName = "ModifyCallingCircleMembers", action = "http://comverse-in.com/prepaid/ccws/ModifyCallingCircleMembers")
    @RequestWrapper(localName = "ModifyCallingCircleMembers", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifyCallingCircleMembers")
    @ResponseWrapper(localName = "ModifyCallingCircleMembersResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ModifyCallingCircleMembersResponse")
    @WebResult(name = "ModifyCallingCircleMembersResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfCircleOperationResponse modifyCallingCircleMembers(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.ArrayOfCircleMemberOperation request
    );

    @WebMethod(operationName = "RetrieveAccumulatorValue", action = "http://comverse-in.com/prepaid/ccws/RetrieveAccumulatorValue")
    @RequestWrapper(localName = "RetrieveAccumulatorValue", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveAccumulatorValue")
    @ResponseWrapper(localName = "RetrieveAccumulatorValueResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveAccumulatorValueResponse")
    @WebResult(name = "RetrieveAccumulatorValueResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveAccumulatorValueResponse2 retrieveAccumulatorValue(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveAccumulatorValueRequest request
    );

    @WebMethod(operationName = "RetrievePostpaidBilledBalance", action = "http://comverse-in.com/prepaid/ccws/RetrievePostpaidBilledBalance")
    @RequestWrapper(localName = "RetrievePostpaidBilledBalance", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrievePostpaidBilledBalance")
    @ResponseWrapper(localName = "RetrievePostpaidBilledBalanceResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrievePostpaidBilledBalanceResponse")
    @WebResult(name = "RetrievePostpaidBilledBalanceResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.BilledBalance retrievePostpaidBilledBalance(
        @WebParam(name = "subscriberId", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberId,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity
    );

    /**
     * Adds a member to a group account.
     */
    @WebMethod(operationName = "CreateGroupAccount", action = "http://comverse-in.com/prepaid/ccws/CreateGroupAccount")
    @RequestWrapper(localName = "CreateGroupAccount", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateGroupAccount")
    @ResponseWrapper(localName = "CreateGroupAccountResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.CreateGroupAccountResponse")
    public void createGroupAccount(
        @WebParam(name = "groupAccountCreate", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.GroupAccountCreate groupAccountCreate
    );

    @WebMethod(operationName = "RetrieveCallingCircles", action = "http://comverse-in.com/prepaid/ccws/RetrieveCallingCircles")
    @RequestWrapper(localName = "RetrieveCallingCircles", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveCallingCircles")
    @ResponseWrapper(localName = "RetrieveCallingCirclesResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveCallingCirclesResponse")
    @WebResult(name = "RetrieveCallingCirclesResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveCallingCirclesResponse2 retrieveCallingCircles(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RetrieveCallingCirclesRequest request
    );

    /**
     * Removes a member from a group account.
     */
    @WebMethod(operationName = "RemoveMemberFromGroup", action = "http://comverse-in.com/prepaid/ccws/RemoveMemberFromGroup")
    @RequestWrapper(localName = "RemoveMemberFromGroup", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RemoveMemberFromGroup")
    @ResponseWrapper(localName = "RemoveMemberFromGroupResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.RemoveMemberFromGroupResponse")
    public void removeMemberFromGroup(
        @WebParam(name = "subscriberID", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String subscriberID,
        @WebParam(name = "identity", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String identity
    );

    @WebMethod(operationName = "SetUserConfig", action = "http://comverse-in.com/prepaid/ccws/SetUserConfig")
    @RequestWrapper(localName = "SetUserConfig", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SetUserConfig")
    @ResponseWrapper(localName = "SetUserConfigResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SetUserConfigResponse")
    public void setUserConfig(
        @WebParam(name = "config", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String config
    );

    /**
     * UnReserves the Voucher based on the card number
     */
    @WebMethod(operationName = "UnReserveVoucher", action = "http://comverse-in.com/prepaid/ccws/UnReserveVoucher")
    @RequestWrapper(localName = "UnReserveVoucher", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UnReserveVoucher")
    @ResponseWrapper(localName = "UnReserveVoucherResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.UnReserveVoucherResponse")
    @WebResult(name = "UnReserveVoucherResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public com.gnv.vnm.selfcare.core.adapter.rtbs.ws.VoucherEntity unReserveVoucher(
        @WebParam(name = "secreteCode", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        java.lang.String secreteCode
    );

    /**
     * Applies requested offer to subscriber
     */
    @WebMethod(operationName = "SubscribeOffer", action = "http://comverse-in.com/prepaid/ccws/SubscribeOffer")
    @RequestWrapper(localName = "SubscribeOffer", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SubscribeOffer")
    @ResponseWrapper(localName = "SubscribeOfferResponse", targetNamespace = "http://comverse-in.com/prepaid/ccws", className = "com.gnv.vnm.selfcare.core.adapter.rtbs.ws.SubscribeOfferResponse")
    @WebResult(name = "SubscribeOfferResult", targetNamespace = "http://comverse-in.com/prepaid/ccws")
    public boolean subscribeOffer(
        @WebParam(name = "request", targetNamespace = "http://comverse-in.com/prepaid/ccws")
        com.gnv.vnm.selfcare.core.adapter.rtbs.ws.OfferSubscribeRequest request
    );
}
