package com.gnv.vnm.selfcare.core.adapter.sv.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-06-12T16:43:05.350+07:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.intecbilling.com/HCPT/prepaid_soap", name = "CommonPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CommonPortType {

    @WebMethod(operationName = "MigratedServiceRequest", action = "MigratedService")
    @RequestWrapper(localName = "MigratedServiceRequest", targetNamespace = "http://www.intecbilling.com/HCPT/prepaid_soap", className = "com.gnv.vnm.selfcare.core.adapter.sv.ws.MigratedServiceRequest")
    @ResponseWrapper(localName = "MigratedServiceResponse", targetNamespace = "http://www.intecbilling.com/HCPT/prepaid_soap", className = "com.gnv.vnm.selfcare.core.adapter.sv.ws.MigratedServiceResponse")
    @WebResult(name = "Routing", targetNamespace = "http://www.intecbilling.com/HCPT/prepaid_soap")
    public java.lang.String migratedServiceRequest(
        @WebParam(name = "MSISDN", targetNamespace = "http://www.intecbilling.com/HCPT/prepaid_soap")
        java.lang.String msisdn
    );
}
